github:
  - judahsullivan

open_collective:
  - zenithbuild

custom:
  - https://github.com/sponsors/judahsullivan
  - https://opencollective.com/zenithbuild
  - https://github.com/orgs/zenithbuild/discussions
